---
extends: [standard, plugin:mocha/recommended]
plugins: [mocha]
env:
  node: true
  mocha: true
rules:
  space-before-function-paren: ["error", {
    "anonymous": "never",
    "named": "never",
    "asyncArrow": "always"]
